[package]
name = "fotos-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
thiserror = "1.0"
image = { version = "0.24", default-features = false, features = ["jpeg", "png"] }
walkdir = "2.4"
rusqlite = { version = "0.30", features = ["bundled"] }
