[package]
name = "fotos-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
thiserror = "1.0"
# WARNING: maintain 'pure Rust' and 'platform-independent' constraints.
# DO NOT add features that depend on system dynamic libraries (e.g., dav1d, rav1e, etc.)
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
walkdir = "2.4"
rusqlite = { version = "0.30", features = ["bundled"] }
kamadak-exif = "0.5"
image_hasher = "3.0.0"
blake3 = "1.5"
serde = { version = "1.0", features = ["derive"] }
